name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy (${{ matrix.config.stack_name }}, ${{ matrix.config.host }})
    runs-on: self-hosted
    strategy:
      matrix:
        config:
          - { host: '192.168.2.121', stack_name: 'uptime-kuma' }
          - { host: '192.168.2.121', stack_name: 'watchtower' }
          - { host: '192.168.2.121', stack_name: 'n8n-cloudflared' }

    env:
      DOCKER_HOST: tcp://${{ matrix.config.host }}:2375
      DOCKER_CONTEXT_NAME: ${{ matrix.config.stack_name }}-ctx
      DOCKER_COMPOSE_FILE: ${{ matrix.config.stack_name }}.yml
      DOCKER_PROJECT_NAME: ${{ matrix.config.stack_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker context
        run: |
          docker context \
            create ${{ env.DOCKER_CONTEXT_NAME }} \
            --docker host=${{ env.DOCKER_HOST }}

      - name: Inject secrets (n8n-cloudflared)
        if: env.DOCKER_PROJECT_NAME == 'n8n-cloudflared'
        run: |
          echo "${{ secrets.N8N_SECRETS }}" >> $GITHUB_ENV

      - name: Deploy with Docker Compose
        run: |
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} compose --file ${{ env.DOCKER_COMPOSE_FILE }} pull
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} compose --file ${{ env.DOCKER_COMPOSE_FILE }} \
            --project-name ${{ env.DOCKER_PROJECT_NAME }} up -d --remove-orphans

      - name: Cleanup Docker context
        if: always()
        run: |
          docker context rm ${{ env.DOCKER_CONTEXT_NAME }} --force
